theme: jekyll-theme-dinky
title: aaaronic.com (formerly aaroneo.us)
description: A side-project for a bored developer with little actual free-time on his hands. So little time, in fact, that this site often goes years with no updates.

plugins:
  - jekyll-seo-tag
